### ISSUE TITLE
Some examples do not contain target word in both sentences

### ISSUE THREAD

**Issue by nvanva** [juliarodina/RuSemShift#2]
For instance, in 
https://github.com/juliarodina/RuSemShift/blob/master/rusemshift_1/raw_annotations.tsv

![image](https://user-images.githubusercontent.com/9987540/107885028-f376c200-6f08-11eb-8a7d-130c8a4f09bf.png)

**Comment by nvanva** [comment]
There are about 10% and 12% of such examples in https://github.com/juliarodina/RuSemShift/blob/master/rusemshift_1/raw_annotations.tsv and https://github.com/juliarodina/RuSemShift/blob/master/rusemshift_2/raw_annotations.tsv
so they are not insufficiently few.

**Comment by akutuzov** [comment]
In your example, the target word "богадельня" **is** present in both sentences, in different inflected forms: "**богадельню**" and "**богаделен**".
It is just that in the first sentence the word is not surrounded with the bold and italics HTML tags (due to technical issues during the example generation process). But it did not influence the annotation.

**Comment by nvanva** [comment]
Yes, you are right, sorry for mistake. But shouldn't we open an issue about tags then?

**Comment by akutuzov** [comment]
Pull requests are welcome :)
But HTML tags are not part of the dataset anyway. They were used only to help the annotators a bit.
